### ISSUE TITLE
Please support getting MIME encodings

### ISSUE THREAD

**Issue by autarch** [houseabsolute/File-LibMagic#10]
Migrated from [rt.cpan.org #54843](https://rt.cpan.org/Ticket/Display.html?id=54843) (status was 'open')

Requestors:
* rrt@sc3d.org

From rrt@sc3d.org on 2010-02-21 18:26:48:

Recent file releases support getting MIME encodings; please add support
to File::LibMagic.

**Comment by autarch** [comment]
From drolsky@cpan.org (@autarch) on 2013-09-02 19:12:40:

On Sun Feb 21 13:26:48 2010, rrt wrote:
> Recent file releases support getting MIME encodings; please add support
> to File::LibMagic.

I've just taken over this module. You might not remember what this was about but I'll ask anyway ...

Did you want a way to get _just_ the encoding or do you just want it included in the mime type. If it's the latter, that's already happening.

**Comment by autarch** [comment]
From rrt@sc3d.org on 2013-09-02 20:32:02:

On 2 September 2013 20:12, Dave Rolsky via RT <bug-File-LibMagic@rt.cpan.org
> wrote:

> <URL: https://rt.cpan.org/Ticket/Display.html?id=54843 >
>
> On Sun Feb 21 13:26:48 2010, rrt wrote:
> > Recent file releases support getting MIME encodings; please add support
> > to File::LibMagic.
>
> I've just taken over this module. You might not remember what this was
> about but I'll ask anyway ...
>
> Did you want a way to get _just_ the encoding or do you just want it
> included in the mime type. If it's the latter, that's already happening.
>

I meant the former: just get the encoding.

-- 
http://rrt.sc3d.org

**Comment by autarch** [comment]
This has been possible for a while with the current API.

**Comment by rrthomas** [comment]
Thanks very much for pointing this out; at last I can use it!
