### ISSUE TITLE
add API for calling magic_setparam to change recursion limits

### ISSUE THREAD

**Issue by pabs3** [houseabsolute/File-LibMagic#14]
At work we found a [situation](https://bugs.debian.org/928009) where the default recursion limits were resulting in an error when detecting some JPEG files. We discovered a workaround of setting the [name recursion limit](https://manpages.debian.org/buster/libmagic-dev/libmagic.3.en.html#MAGIC_PARAM_NAME_MAX) slightly higher, but we were not able to apply this workaround to our internal File::LibMagic based tool because File::LibMagic lacks a way to set the recursion limits.

It would be great to have this part of the libmagic API exposed by File::LibMagic for situations that require workarounds for adjusting the recursion limits and other parameters.

**Comment by autarch** [comment]
Yes, this sounds useful. As always, PRs are welcome. I should note that I only want to see additions to the newest (OO) version of the API. It seems like this should ideally be a constructor parameter. I think this would be quite easy to implement, as the XS side of this module is very simple.

**Comment by pabs3** [comment]
Great. We are discussing internally what approach to take here.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
I've added a WIP patch for this in PR #15.
